import { Printer, Files, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";

export default function CheckRegister({ checks, selected, onToggle, onPrint, onDelete, deletingId, onBatchPrint, loading }) {
  return <section className="bg-card border border-border rounded-2xl overflow-hidden min-w-0">
    <div className="px-5 py-4 border-b border-border flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">Control register</p><h2 className="text-xl font-bold">Saved Checks</h2></div>{selected.size > 0 && <Button size="sm" onClick={onBatchPrint}><Files /> Batch Print ({selected.size})</Button>}</div>
    {loading ? <p className="py-16 text-center text-muted-foreground">Loading checks...</p> : checks.length === 0 ? <p className="py-16 text-center text-muted-foreground">No checks saved yet.</p> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/40"><tr><th className="p-3 w-10"></th><th className="p-3 text-left">Check #</th><th className="p-3 text-left">Payee</th><th className="p-3 text-left">Linked Request</th><th className="p-3 text-left">Date</th><th className="p-3 text-right">Amount</th><th className="p-3 text-center">Status</th><th className="p-3"></th></tr></thead><tbody>{checks.map(check => <tr key={check.id} className="border-t border-border hover:bg-muted/20"><td className="p-3"><Checkbox checked={selected.has(check.id)} disabled={check.status === "voided"} onCheckedChange={() => onToggle(check.id)} /></td><td className="p-3 font-mono font-semibold">{check.check_number}</td><td className="p-3"><p className="font-medium">{check.payee}</p><p className="text-xs text-muted-foreground">{check.bank_name}</p></td><td className="p-3 text-xs text-muted-foreground">{check.payment_request_numbers?.length ? check.payment_request_numbers.join(", ") : "Independent"}</td><td className="p-3 text-muted-foreground whitespace-nowrap">{check.check_date}</td><td className="p-3 text-right font-mono font-bold">₱{Number(check.amount || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td><td className="p-3 text-center"><Badge variant={check.status === "printed" ? "default" : "outline"} className="capitalize">{check.status}</Badge></td><td className="p-3 text-right"><div className="flex justify-end gap-1"><Button variant="ghost" size="sm" disabled={check.status === "voided"} onClick={() => onPrint(check)}><Printer /> Print</Button>{check.status === "saved" && <Button variant="ghost" size="sm" className="text-destructive hover:text-destructive" disabled={deletingId === check.id} onClick={() => onDelete(check)}><Trash2 /> {deletingId === check.id ? "Deleting..." : "Delete"}</Button>}</div></td></tr>)}</tbody></table></div>}
  </section>;
}