import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
import { format } from "date-fns";
import { Plus, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import AddCustomerAdvanceDialog from "./AddCustomerAdvanceDialog";
import ApplyCustomerAdvanceDialog from "./ApplyCustomerAdvanceDialog";

export default function CustomerAdvances() {
  const [adding, setAdding] = useState(false); const [applying, setApplying] = useState(null); const qc = useQueryClient();
  const { data: advances = [], isLoading } = useQuery({ queryKey: ["customer_advances"], queryFn: () => base44.entities.CustomerAdvance.list("-received_date", 1000) });
  const { data: clients = [] } = useQuery({ queryKey: ["clients"], queryFn: () => base44.entities.Client.list("client_name", 1000) });
  const { data: bankAccounts = [] } = useQuery({ queryKey: ["bankaccounts"], queryFn: () => base44.entities.BankAccount.list("-created_date", 100) });
  const { data: receivables = [] } = useQuery({ queryKey: ["advance_receivables", applying?.client_id], queryFn: () => base44.entities.Receivable.filter({ client_name: applying.client_name }, "-due_date", 1000), enabled: !!applying });
  const refresh = () => { qc.invalidateQueries({ queryKey: ["customer_advances"] }); qc.invalidateQueries({ queryKey: ["receivables"] }); };
  const create = useMutation({ mutationFn: async data => { const advance = await base44.entities.CustomerAdvance.create(data); await base44.entities.Transaction.create({ description: `Customer advance — ${data.client_name}${data.reference ? ` · ${data.reference}` : ""}`, amount: data.amount, type: "income", category: "other", chart_of_account: "Customer Advances", bank_account_id: data.bank_account_id || "", date: data.received_date, status: "completed" }); return advance; }, onSuccess: refresh });
  const apply = async (receivable, amount, date) => { const paid = (receivable.amount_paid || 0) + amount; const balance = (applying.available_balance || 0) - amount; await Promise.all([base44.entities.Receivable.update(receivable.id, { amount_paid: paid, status: paid >= receivable.amount ? "paid" : "partially_paid", payment_history: [...(receivable.payment_history || []), { collection_date: date, amount, reference: applying.reference || "", notes: "Applied from customer advance", is_advance_payment: true }] }), base44.entities.CustomerAdvance.update(applying.id, { applied_amount: (applying.applied_amount || 0) + amount, available_balance: balance, status: balance <= 0 ? "fully_applied" : "partially_applied", application_history: [...(applying.application_history || []), { receivable_id: receivable.id, invoice_number: receivable.invoice_number || "", amount, application_date: date }] })]); refresh(); };
  const available = advances.reduce((s, a) => s + (a.available_balance || 0), 0); const openReceivables = receivables.filter(r => r.status !== "paid" && (r.amount || 0) > (r.amount_paid || 0));
  return <div className="space-y-4"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">₱{available.toLocaleString(undefined, { minimumFractionDigits: 2 })} available customer advances</p><Button size="sm" onClick={() => setAdding(true)}><Plus className="w-4 h-4" /> Record Advance</Button></div>
    {isLoading ? <p className="py-12 text-center text-muted-foreground">Loading...</p> : advances.length === 0 ? <p className="py-12 text-center text-muted-foreground">No customer advances yet</p> : <div className="overflow-hidden rounded-xl border border-border bg-card"><table className="w-full text-sm"><thead className="bg-muted/50"><tr>{["Client", "Date", "Reference", "Advance", "Applied", "Available", "Status", ""].map(h => <th key={h} className="px-4 py-2 text-left text-xs font-semibold uppercase text-muted-foreground">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{advances.map(a => <tr key={a.id}><td className="px-4 py-3 font-medium">{a.client_name}</td><td className="px-4 py-3 text-muted-foreground">{format(new Date(a.received_date), "MMM d, yyyy")}</td><td className="px-4 py-3 text-muted-foreground">{a.reference || "—"}</td><td className="px-4 py-3">₱{(a.amount || 0).toLocaleString()}</td><td className="px-4 py-3">₱{(a.applied_amount || 0).toLocaleString()}</td><td className="px-4 py-3 font-bold">₱{(a.available_balance || 0).toLocaleString()}</td><td className="px-4 py-3"><Badge variant="outline">{(a.status || "available").replace(/_/g, " ")}</Badge></td><td className="px-4 py-3 text-right"><Button size="sm" variant="outline" disabled={(a.available_balance || 0) <= 0} onClick={() => setApplying(a)}><Send className="w-3 h-3" /> Apply</Button></td></tr>)}</tbody></table></div>}
    <AddCustomerAdvanceDialog open={adding} onOpenChange={setAdding} clients={clients} bankAccounts={bankAccounts} onSubmit={create.mutateAsync} /><ApplyCustomerAdvanceDialog open={!!applying} onOpenChange={v => !v && setApplying(null)} advance={applying} receivables={openReceivables} onSubmit={apply} /></div>;
}